blank_issues_enabled: true
contact_links:
  - name: 💬 Diskussionen
    url: https://github.com/loopwaveeeeee/sabsteckapi/discussions
    about: Für allgemeine Fragen und Diskussionen
  - name: 📚 Dokumentation
    url: https://github.com/loopwaveeeeee/sabsteckapi/blob/main/PROJECT.md
    about: Projektdokumentation und -übersicht
